### PR TITLE
chore: add APIScan

### PR DESCRIPTION
**Pull request by rzhao271**

### CODE REVIEW

**Comment by rzhao271** [comment]
Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259243&view=results

**Comment by rzhao271** [comment]
Verification build
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259248&view=results

**Comment by rzhao271** [comment]
This one's good https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259251&view=results

**Comment by rzhao271** [comment]
Latest confirmation build https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259457&view=results

**Review by sbatten — APPROVED** [review]

**Pull request merged**
