### PR TITLE
fix: APIScan reports Documentation Not Found errors

### PR DESCRIPTION
**Pull request by rzhao271**
This PR aims to fix APIScan Documentation Not Found errors in order to bring our prebuilt version of zeromq into compliance.

### Changes

The APIScan errors come from wepoll, which is an upstream dependency of zeromq-prebuilt:
zeromq-prebuilt -> zeromq.js -> libzmq -> wepoll.

As a result, this PR is fairly involved and involves:
- Creating a patch for libzmq that adjusts the CMake file and wepoll source code to remove the KeyedEvent references.
- Modifying the zeromq.js build script to apply the libzmq patch.
- ~~Modifying zeromq.js/binding.gyp to add a new dependency on synchronization.lib~~
- Modifying the zeromq.js patch to contain those new changes.

### Next steps and blockers

I have set this PR to July due to the following blockers:
- We haven't tested this change in Jupyter, and I'd rather merge this in early next month in case of compatibility issues or issues with the new wepoll implementation.
- We're currently blocked on waiting for APIScan to support our current Azure infrastructure setup. I have commented out the APIScan tasks for now, but we don't currently have the ability to check whether this PR fixes the APIScan Documentation Not Found errors.

### CODE REVIEW

**Comment by deepak1556** [comment]
For the alpine failures, you can change to mcr base images `mcr.microsoft.com/mirror/docker/library/alpine:3.16` and download node binaries from https://github.com/microsoft/vscode-node/releases/tag/v20.14.0-282653 to avoid the rate limits.

**Comment by rzhao271** [comment]
I'm able to run the Alpine steps locally on Windows with pwsh, but the steps fail in CI.

Example command that works on Windows: `docker run --volume ${pwd}:/app --workdir /app --privileged builderx64 sh -c "$env:DOCKERCMD"` where `pwd=C:\Users\raymondzhao\work\zeromq-prebuilt\zeromq.js`, `DOCKERCMD=apk add --no-cache pkgconfig curl tar python3 make gcc g++ cmake musl-dev npm patch && npm i -g pnpm@latest-8 && pnpm install && npm run prebuild`

I could try using a Windows agent and pwsh tomorrow, but let me know if you've other ideas on what might be happening @deepak1556

**Comment by deepak1556** [comment]
Seems like a permission issue, try creating a sudo user and run the container steps via that user https://github.com/nodejs/docker-node/blob/2358b05a03119c1342a4a1cb8ffb21b026737029/18/alpine3.19/Dockerfile#L5-L6. Also see if updating to the latest npm helps

**Comment by rzhao271** [comment]
I have fixed the Alpine builds.
There are still a few action items I'd like to complete before I merge this PR:
- [ ] Wait for Guardian to update their APIScan to the newest version so that we can use our Service Connection to authenticate into it. Currently, the APIScan task is commented out on all of our pipelines. ETA 1 to 2 weeks from now.
- [ ] Confirm with a working APIScan run that the patch removes our dependency on undocumented APIs.
- [ ] Perform another round of testing in wepoll, libzmq, and maybe even jupyter to confirm that the patch works as expected.

**Comment by rzhao271** [comment]
Moving to August. I increased the parameters of `test-reflock.c` and found out that my current implementation deadlocks.
I noticed a very interesting feature of `NtReleaseKeyedEvent`, which is that it actually waits for another thread to call `NtWaitForKeyedEvent` ([source](https://undocumented-ntinternals.github.io/UserMode/Undocumented%20Functions/NT%20Objects/KeyedEvent/NtReleaseKeyedEvent.html)). Therefore, `NtWaitForKeyedEvent` and `NtReleaseKeyedEvent` wait for each other to be called before proceeding.

I'm currently experimenting with adding condition variables to each reflock struct instead of using `WaitOnAddress` to represent the `reflock_unref()` threads and the `reflock_unref_and_destroy()` thread waiting for each other.

**Comment by rzhao271** [comment]
I'm a lot more confident in my changes now, though would still like to wait until APIScan is enabled again to check that this PR resolves the Documentation Not Found issue.
I plan to check the wepoll test coverage from libzmq and jupyter during debt week.

**Comment by rzhao271** [comment]
I have confirmed that this PR resolves the Documentation Not Found issue!

**Comment by rzhao271** [comment]
Verification build https://dev.azure.com/monacotools/Monaco/_build/results?buildId=287328&view=results

I also haven't yet confirmed test coverage of wepoll in libzmq and jupyter, but I did test the wepoll changes using wepoll's test_reflock.c and confirmed that there's no deadlock (the older WaitOnAddress implementation had deadlocks).

**Comment by rzhao271** [comment]
@deepak1556 this PR is ready to review. There are still Missing Symbols APIScan results, but I'd like to resolve those in a future PR.

**Comment by rzhao271** [comment]
The last verification build failed due to a GitHub outage.
Latest verification build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=288203&view=results

**Review by deepak1556 — APPROVED** [review]
LGTM on build file changes, haven't reviewed the wepoll changes. No reason to block this PR given the discussion in upstream repo.

**Pull request merged**
